### ISSUE TITLE
pitest fails on module grammar

### ISSUE THREAD

**Issue by khmarbaise** [khmarbaise/jacem#3]
Currently pitest fails with the following:
```
[INFO] Defaulting target tests to match packages in test build directory
22:04:28 PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
22:04:28 PIT >> INFO : Incremental analysis reduced number of mutations by 0
22:04:28 PIT >> INFO : Created  57 mutation test units in pre scan
22:04:29 PIT >> INFO : Sending 22 test classes to minion
22:04:29 PIT >> INFO : Sent tests to minion
22:04:29 PIT >> INFO : MINION : 22:04:29 PIT >> INFO : Checking environment
22:04:29 PIT >> INFO : MINION : 22:04:29 PIT >> SEVERE : Error calculating coverage. Process will exit.
22:04:29 PIT >> INFO : MINION : org.junit.platform.commons.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
22:04:29 PIT >> INFO : MINION : 	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:296)
22:04:29 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:48)
22:04:29 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:105)
22:04:29 PIT >> INFO : MINION : 	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:75)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.junit5.JUnit5TestUnitFinder.<init>(JUnit5TestUnitFinder.java:54)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.junit5.JUnit5Configuration.testUnitFinder(JUnit5Configuration.java:43)
22:04:29 PIT >> SEVERE : Coverage generator Minion exited abnormally due to UNKNOWN_ERROR
22:04:29 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnits(FindTestUnits.java:56)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.getTestUnits(FindTestUnits.java:40)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.testapi.execute.FindTestUnits.findTestUnitsForAllSuppliedClasses(FindTestUnits.java:29)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:155)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:136)
22:04:29 PIT >> INFO : MINION : 	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:83)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JaCeM Parent 0.1.0-SNAPSHOT:
[INFO] 
[INFO] JaCeM Parent ....................................... SUCCESS [  1.764 s]
[INFO] JaCeM : Emulators .................................. SUCCESS [  0.025 s]
[INFO] JaCeM : Emulators : Common ......................... SUCCESS [  9.248 s]
[INFO] JaCeM : Emulators : 6502 ........................... SUCCESS [01:41 min]
[INFO] JaCeM : Emulators : 8085 ........................... SUCCESS [  2.480 s]
[INFO] JaCeM : CrALinkR Parent ............................ SUCCESS [  0.016 s]
[INFO] JaCeM : CrALinkR : Grammar ......................... FAILURE [  3.466 s]
[INFO] JaCeM : CrALinkR : Parser .......................... SKIPPED
[INFO] JaCeM : CrALinkR : ASM ............................. SKIPPED
[INFO] JaCeM : CrALinkR : CLI ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:58 min
[INFO] Finished at: 2021-05-25T22:04:29+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.6.6:mutationCoverage (default-cli) on project grammar: Execution default-cli of goal org.pitest:pitest-maven:1.6.6:mutationCoverage failed: Coverage generation minion exited abnormally!
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : AdoptOpenJDK
[ERROR] Version : 11.0.11+9
[ERROR] Uptime : 119517
[ERROR] Input -> 
[ERROR]  1 : -Djava.awt.headless=true
[ERROR]  2 : -Dclassworlds.conf=/Users/khmarbaise/tools/maven/bin/m2.conf
[ERROR]  3 : -Dmaven.home=/Users/khmarbaise/tools/maven
[ERROR]  4 : -Dlibrary.jansi.path=/Users/khmarbaise/tools/maven/lib/jansi-native
[ERROR]  5 : -Dmaven.multiModuleProjectDirectory=/Users/khmarbaise/ws-git-soebes/archetype/jacem
[ERROR] BootClassPathSupported : false
[ERROR] 
[ERROR] 
[ERROR] Please copy and paste the information and the complete stacktrace below when reporting an issue
[ERROR] VM : OpenJDK 64-Bit Server VM
[ERROR] Vendor : AdoptOpenJDK
[ERROR] Version : 11.0.11+9
[ERROR] Uptime : 119517
[ERROR] Input -> 
[ERROR]  1 : -Djava.awt.headless=true
[ERROR]  2 : -Dclassworlds.conf=/Users/khmarbaise/tools/maven/bin/m2.conf
[ERROR]  3 : -Dmaven.home=/Users/khmarbaise/tools/maven
[ERROR]  4 : -Dlibrary.jansi.path=/Users/khmarbaise/tools/maven/lib/jansi-native
[ERROR]  5 : -Dmaven.multiModuleProjectDirectory=/Users/khmarbaise/ws-git-soebes/archetype/jacem
[ERROR] BootClassPathSupported : false
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :grammar
```

Recheck: https://blog.pitest.org/pitest-pr-setup/

**Comment by khmarbaise** [comment]
Fixed with b336b044b6583b45e3529df238e5e89794d9681e
